# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rgabo-readability}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabor Ratky"]
  s.date = %q{2010-05-16}
  s.description = %q{Extends Nokogiri::HTML::Document to run Arc90's Readability script and produces easy to read HTML documents.}
  s.email = %q{rgabo@rgabostyle.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example.rb",
     "lib/readability.rb",
     "lib/readability/harmonizable.rb",
     "lib/readability/js/readability.js",
     "lib/readability/readable.rb",
     "readability.gems",
     "rgabo-readability.gemspec",
     "spec/files/change_title.js",
     "spec/files/tomdoc-reasonable-ruby-documentation.html",
     "spec/readability/harmonizable_spec.rb",
     "spec/readability/readable_spec.rb",
     "spec/readability_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rgabo/readability}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Run Arc90's Readability on Nokogiri documents}
  s.test_files = [
    "spec/readability/harmonizable_spec.rb",
     "spec/readability/readable_spec.rb",
     "spec/readability_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<harmony>, ["= 0.5.5"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<harmony>, ["= 0.5.5"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<harmony>, ["= 0.5.5"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4"])
  end
end

